import type { Product, Category } from '../types'

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'The Midnight Library',
    category: 'fiction',
    price: 650,
    sale_price: null,
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=80',
    colors: ['#1a1a2e', '#16213e', '#0f3460'],
    sizes: [1, 2, 3],
    badge: 'new',
    stock: 24,
    description: 'A dazzling novel about all the lives you could have lived. Between life and death there is a library, and within that library, the shelves go on forever.',
  },
  {
    id: 2,
    name: 'Sapiens',
    category: 'history',
    price: 890,
    sale_price: null,
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80',
    colors: ['#f5a623', '#d4891a', '#111'],
    sizes: [1, 2, 3, 4],
    badge: null,
    stock: 40,
    description: 'A Brief History of Humankind. From a renowned historian comes a groundbreaking narrative of humanity\'s creation and evolution.',
  },
  {
    id: 3,
    name: 'A Brief History of Time',
    category: 'science',
    price: 750,
    sale_price: 550,
    image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&q=80',
    colors: ['#2563eb', '#111', '#f04048'],
    sizes: [1, 2, 3],
    badge: 'sale',
    stock: 12,
    description: 'Stephen Hawking\'s landmark volume on the structure, origin, development, and eventual fate of the Universe.',
  },
  {
    id: 4,
    name: 'Atomic Habits',
    category: 'non-fiction',
    price: 720,
    sale_price: null,
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&q=80',
    colors: ['#111', '#3b82f6', '#f04048'],
    sizes: [1, 2, 3, 4],
    badge: null,
    stock: 30,
    description: 'An easy and proven way to build good habits and break bad ones. Tiny changes, remarkable results.',
  },
  {
    id: 5,
    name: 'Dune',
    category: 'fiction',
    price: 980,
    sale_price: null,
    image: 'https://images.unsplash.com/photo-1495640452828-3df6795cf69b?w=600&q=80',
    colors: ['#dc2626', '#111', '#fff'],
    sizes: [1, 2, 3, 4],
    badge: 'new',
    stock: 8,
    description: 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides — the heir to a noble family tasked with ruling the universe\'s most dangerous planet.',
  },
  {
    id: 6,
    name: 'Guns, Germs, and Steel',
    category: 'history',
    price: 820,
    sale_price: 650,
    image: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600&q=80',
    colors: ['#fff', '#f5e6d3', '#111'],
    sizes: [1, 2, 3],
    badge: 'sale',
    stock: 20,
    description: 'A Pulitzer Prize-winning analysis of why Western civilizations came to dominate the rest of the world.',
  },
  {
    id: 7,
    name: 'The Selfish Gene',
    category: 'science',
    price: 690,
    sale_price: null,
    image: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=600&q=80',
    colors: ['#e5ff00', '#111'],
    sizes: [1, 2, 3],
    badge: 'new',
    stock: 5,
    description: 'Richard Dawkins\' classic exposition of evolutionary theory, told from the gene\'s eye view of life, is both riveting and controversial.',
  },
  {
    id: 8,
    name: 'Thinking, Fast and Slow',
    category: 'non-fiction',
    price: 760,
    sale_price: null,
    image: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=600&q=80',
    colors: ['#22c55e', '#fff', '#111'],
    sizes: [1, 2, 3, 4],
    badge: null,
    stock: 16,
    description: 'Daniel Kahneman reveals the two systems that drive the way we think — and how to make better decisions by understanding them.',
  },
]

export const CATEGORIES: Category[] = ['all', 'fiction', 'non-fiction', 'science', 'history']

// Edition labels
export const EDITION_LABELS: Record<number, string> = {
  1: 'Paperback',
  2: 'Hardcover',
  3: 'eBook',
  4: 'Audiobook',
}
